# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'terr&eacute; bon'
tagline:             ' / the good earth'
description:         'I am an experienced data and machine learning architect, entrepreneur, and musician (CDBaby <a href="https://store.cdbaby.com/cd/thefreddiekingdom">here</a>) I like data and have a funny story to share: while technology promises abundance it has left us wanting. More than technology we need <a href="https://www.ted.com/talks/matthieu_ricard_on_the_habits_of_happiness">compassion.</a>'
url:                 https://geraldmc.github.io/
baseurl:             ''
paginate:            5
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]


# About/contact
author:
  name:              Gerald McCollam
  url:               https://geraldmc.github.io/
  email:             gerald.mccollam@gmail.com

# Github
#github:
  repo:           https://github.com/geraldmc/

# Custom vars
version:             0.0.1
timezone:            'America/Chicago'
show_drafts:         False

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-gist

safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown:     kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

license:             CC BY 4.0
license_url:         http://creativecommons.org/licenses/by/4.0/legalcode


